import React, { useState } from 'react';
import { Code, Check, Zap, Copy } from 'lucide-react';
import sdk from '@stackblitz/sdk';

interface LivePreviewProps {
  code: string;
}

export const LivePreview: React.FC<LivePreviewProps> = ({ code }) => {
  const [copySuccess, setCopySuccess] = useState(false);

  const copyCode = () => {
    if (!code) return;
    navigator.clipboard.writeText(code);
    setCopySuccess(true);
    setTimeout(() => setCopySuccess(false), 2000);
  };

  const openStackBlitz = () => {
    if (!code) return;

    // Define the StackBlitz project
    const project = {
      title: 'Design2React Component',
      description: 'AI Generated React Component',
      template: 'create-react-app',
      files: {
        'public/index.html': `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Design2React Demo</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        theme: {
          extend: {
            fontFamily: {
              sans: ['Inter', 'sans-serif'],
              mono: ['JetBrains Mono', 'monospace'],
            },
          }
        }
      }
    </script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
        `,
        'src/index.js': `
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
        `,
        'src/App.tsx': code,
        'package.json': JSON.stringify({
          name: "design2react-demo",
          version: "1.0.0",
          description: "Generated by Design2React",
          dependencies: {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "lucide-react": "^0.292.0",
            "react-scripts": "5.0.1"
          },
          scripts: {
            "start": "react-scripts start",
            "build": "react-scripts build",
            "test": "react-scripts test",
            "eject": "react-scripts eject"
          },
          browserslist: {
            production: [">0.2%", "not dead", "not op_mini all"],
            development: ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
          }
        }, null, 2)
      },
      settings: {
        compile: {
          trigger: 'auto',
          clearConsole: false,
        },
      },
    };

    // Open in new window using the SDK
    sdk.openProject(project as any, { openFile: 'src/App.tsx', newWindow: true });
  };

  return (
    <div className="w-full h-full flex flex-col bg-gray-900 border-b border-gray-800">
      <div className="h-12 bg-gray-800/50 border-b border-gray-700 flex items-center justify-between px-4 select-none backdrop-blur-sm">
         <div className="flex items-center gap-3">
            <span className="text-sm font-semibold text-gray-200 flex items-center gap-2">
                <Code size={16} className="text-blue-400" /> 
                Generated Code
            </span>
         </div>
         <div className="flex items-center gap-2">
            <button 
                onClick={copyCode}
                className="flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium bg-gray-700 hover:bg-gray-600 text-gray-200 transition-colors border border-gray-600"
                title="Copy to clipboard"
            >
                {copySuccess ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                {copySuccess ? 'Copied' : 'Copy'}
            </button>
            <button
                onClick={openStackBlitz}
                className="flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium bg-blue-600 hover:bg-blue-500 text-white transition-all shadow-lg shadow-blue-900/30"
                title="Open in StackBlitz to run and edit"
            >
                <Zap size={14} fill="currentColor" />
                Run in StackBlitz
            </button>
         </div>
      </div>
      
      <div className="flex-1 relative bg-gray-950 overflow-hidden group">
        {code ? (
            <div className="absolute inset-0 overflow-auto custom-scrollbar">
                <pre className="p-4 text-sm font-mono leading-relaxed text-gray-300 tab-4">
                    <code>{code}</code>
                </pre>
            </div>
        ) : (
            <div className="absolute inset-0 flex items-center justify-center text-gray-600 flex-col gap-3">
                <div className="w-12 h-12 rounded-full bg-gray-800/50 flex items-center justify-center">
                    <Code size={24} className="opacity-40" />
                </div>
                <p className="text-sm">Waiting for code generation...</p>
            </div>
        )}
      </div>
      <style>{`
        .tab-4 { tab-size: 2; }
        .custom-scrollbar::-webkit-scrollbar { width: 10px; height: 10px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: #0d1117; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #2d3748; border-radius: 5px; border: 2px solid #0d1117; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #4a5568; }
      `}</style>
    </div>
  );
};